name: Bump version

on:
  workflow_dispatch:

jobs:
  bump_version:
    environment: 
      name: local
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    runs-on: ubuntu-latest
    name: "Bump version and create changelog with commitizen"
    outputs:
      version: ${{ steps.version_output.outputs.version }}
    steps:
      - name: Check out
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: "${{ secrets.AGUS_PA }}"

      # Commitizen stuff
      # Note that we need personal account token of an administrator with `repo` authorization to push directly to main branch
      - id: cz
        name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@master
        with:
          github_token: ${{ secrets.AGUS_PA }}
          branch: main
          changelog_increment_filename: body.md
          push: false
          extra_requirements: typing-extensions
      - name: move tag
        run: |
          git tag -f ${{ steps.cz.outputs.version }} HEAD^1

      # Push commit & tag
      # Other option is to use https://github.com/ad-m/github-push-action
      # But we need the atomic operation for pushing the commit and tag
      - name: Push changes
        run: |
          export remote_repo="https://${GITHUB_ACTOR}:${TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
          git push ${remote_repo} --atomic main ${{ steps.cz.outputs.version }}
        env:
          TOKEN: ${{ secrets.AGUS_PA }}

      # Release
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: "body.md"
          tag_name: ${{ steps.cz.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Print Changelog
        run: cat body.md
      - name: Print Version
        id: version_output
        run: |
          echo "Bumped to version ${{ steps.cz.outputs.version }}"
          echo "::set-output version=${{ steps.cz.outputs.version }}"

  deploy_to_staging:
    needs: bump_version
    uses: "aguss787/github-action-test/.github/workflows/deploy_template.yaml@main"
    with:
      commit_id: ${{ needs.bump_version.outputs.version }}
      env: staging
