name: Deploy and send to Sentry

on:
  workflow_dispatch:
  push:
    branches:
      - '*'
    tags:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-20.04

    env:
      version: ${{ ((github.ref_type == 'tag') && github.ref) || github.sha }}

    steps:
      - uses: actions/checkout@v2

      - name: Create Sentry release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
        with:
          environment: production
          version: $version

      - name: Deploying
        run: | 
          echo "Deploying"
          echo "Sentry release: $version"
          

      - name: Finalize Sentry release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
        with:
          environment: production
          version: $version
          finalize: true
