name: deploy

on:
  workflow_dispatch:
    inputs:
      commit_id:
        description: 'Commit id to be deployed'
        required: false
        default: 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Check out
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.commit_id }}
          fetch-depth: 0
          token: "${{ secrets.GITHUB_TOKEN }}"
      - name: deploy
        run: |
          echo deploying
          git log --tags -n 10 > logs
          cat logs
          head CHANGELOG.md -n 100
