name: Deploy

on:
  workflow_dispatch:
    inputs:
      commit_id:
        description: 'Commit id to be deployed'
        required: true
        default: 'main'
      env:
        description: 'env'
        required: true
        default: 'production'
        type: choice
        options:
          - dev
          - staging
          - production

jobs:
  deploy:
      uses: "aguss787/github-action-test/.github/workflows/deploy_template.yaml@main"
      with:
        commit_id: ${{ github.event.inputs.commit_id }}
        env: ${{ github.event.inputs.env }}
