name: Deploy

on:
  workflow_dispatch:
    inputs:
      commit_id:
        description: 'Commit id to be deployed'
        required: false
        default: 'main'
      env:
        description: 'env'
        required: true
        default: 'production' # todo: dropdown

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Deploy
        uses: ${GITHUB_REPOSITORY}/.github/workflows/deploy_template.yaml@${GITHUB_REF}
        with:
          commit_id: ${{ github.event.inputs.commit_id }}
          env: ${{ github.event.inputs.env }}
