name: Testing Env Param
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run'
        type: environment
        required: true
        default: Dev

jobs:
  run-thingy:
    name: Run Something
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.event.inputs.environment || 'Dev' }}
    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
      - name: Dump Job context
        id: job_context_step
        run: echo '${{ toJSON(job) }}'
        
      - name: Print env
        run: |
          echo "env input: ${{ github.event.inputs.environment }}"
      - name: Print env var
        env:
          NAME: ${{ secrets.ENV_NAME }}
        run: |
          echo "Test env name $NAME"
          echo "wut ${{ secrets.ENV_NAME }}"
