name: Unit Test

on:
  workflow_dispatch:
  push:

jobs:
  test:
    name: "Run unit tests"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: "Run tests"
        run: |
          echo "Running unit tests"
