name: Unit Test

on:
  workflow_dispatch:
  push:

jobs:
  test:
    name: "Run unit tests"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Test"
        working-directory: tgr-resource-inventory-0.4.2
        run: |
          pwd
          ls

      - name: "Run tests"
        run: |
          echo "Running unit tests"
